### ISSUE TITLE
how can i use it in centos client? 

### ISSUE THREAD

**Issue by nuved** [hudecof/apt-cacher-ng-remap#1]
hello man. i install apt-cacher-ng in ubuntu server... 

but i cant use it for centos client yet :( 

can you guid me, how can i configure yum.conf until yum use mapper?

**Comment by hudecof** [comment]
the package manager is configured to use the apt-cacher-ng as proxy so simply set the proxy server in the yum.conf

```
proxy=http://192.168.11.6:3142
```

**Comment by nuved** [comment]
thx man for answer..
I set it on centos but i just have problem with mirror list repo in centos. I must change repo from mirror list to base url! is there any way, apt-cache-ng handle mirror list in centos?

**Comment by hudecof** [comment]
@nuved 
Ineeded to add this line

    VfilePatternEx: ^(/\?release=[0-9]+&arch=.*|.*/RPM-GPG-KEY-.*|/metalink\?repo=epel\-[0-9]+&arch=.*)$

see the blog https://www.pitt-pladdy.com/blog/_20150720-132951_0100_Home_Lab_Project_apt-cacher-ng_with_CentOS/
